[2025-10-10T23:37:45.129+0200] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: predict_batch_dag.send_batch_predictions scheduled__2025-10-10T21:18:00+00:00 [queued]>
[2025-10-10T23:37:45.131+0200] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: predict_batch_dag.send_batch_predictions scheduled__2025-10-10T21:18:00+00:00 [queued]>
[2025-10-10T23:37:45.131+0200] {taskinstance.py:2193} INFO - Starting attempt 5 of 1
[2025-10-10T23:37:45.137+0200] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): send_batch_predictions> on 2025-10-10 21:18:00+00:00
[2025-10-10T23:37:45.140+0200] {standard_task_runner.py:60} INFO - Started process 48230 to run task
[2025-10-10T23:37:45.164+0200] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'predict_batch_dag', 'send_batch_predictions', 'scheduled__2025-10-10T21:18:00+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/prediction_dag.py', '--cfg-path', '/var/folders/rp/syznybx160jd0kg9k7r_sj8w0000gn/T/tmpaz3fi86s']
[2025-10-10T23:37:45.167+0200] {standard_task_runner.py:88} INFO - Job 125: Subtask send_batch_predictions
[2025-10-10T23:37:45.197+0200] {task_command.py:423} INFO - Running <TaskInstance: predict_batch_dag.send_batch_predictions scheduled__2025-10-10T21:18:00+00:00 [running]> on host ebots-macbook-pro.local
[2025-10-10T23:37:45.245+0200] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='predict_batch_dag' AIRFLOW_CTX_TASK_ID='send_batch_predictions' AIRFLOW_CTX_EXECUTION_DATE='2025-10-10T21:18:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-10T21:18:00+00:00'
[2025-10-10T23:37:45.246+0200] {logging_mixin.py:188} INFO - ðŸ“„ Found CSV file: /Users/ebotfabien/Desktop/school/air_new/dags/destination/data_part_1.csv
[2025-10-10T23:37:45.250+0200] {logging_mixin.py:188} INFO - ðŸ“¦ Sending 10 batch(es)...
[2025-10-11T05:23:10.554+0200] {local_task_job_runner.py:121} ERROR - Received SIGTERM. Terminating subprocesses
[2025-10-11T05:23:10.598+0200] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 48230. PIDs of all processes in the group: [48230]
[2025-10-11T05:23:10.599+0200] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 48230
[2025-10-11T05:23:12.962+0200] {taskinstance.py:1969} INFO - Dependencies not met for <TaskInstance: predict_batch_dag.send_batch_predictions scheduled__2025-10-10T21:18:00+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2025-10-11T05:23:12.964+0200] {taskinstance.py:1969} INFO - Dependencies not met for <TaskInstance: predict_batch_dag.send_batch_predictions scheduled__2025-10-10T21:18:00+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2025-10-11T05:23:12.965+0200] {local_task_job_runner.py:160} INFO - Task is not able to be run
