[2025-10-11T05:23:14.003+0200] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: predict_batch_dag.send_batch_predictions manual__2025-10-10T21:20:20.026271+00:00 [queued]>
[2025-10-11T05:23:14.006+0200] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: predict_batch_dag.send_batch_predictions manual__2025-10-10T21:20:20.026271+00:00 [queued]>
[2025-10-11T05:23:14.006+0200] {taskinstance.py:2193} INFO - Starting attempt 3 of 1
[2025-10-11T05:23:14.010+0200] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): send_batch_predictions> on 2025-10-10 21:20:20.026271+00:00
[2025-10-11T05:23:14.014+0200] {standard_task_runner.py:60} INFO - Started process 57831 to run task
[2025-10-11T05:23:14.019+0200] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'predict_batch_dag', 'send_batch_predictions', 'manual__2025-10-10T21:20:20.026271+00:00', '--job-id', '127', '--raw', '--subdir', 'DAGS_FOLDER/prediction_dag.py', '--cfg-path', '/var/folders/rp/syznybx160jd0kg9k7r_sj8w0000gn/T/tmpru2tdw0n']
[2025-10-11T05:23:14.040+0200] {standard_task_runner.py:88} INFO - Job 127: Subtask send_batch_predictions
[2025-10-11T05:23:14.072+0200] {task_command.py:423} INFO - Running <TaskInstance: predict_batch_dag.send_batch_predictions manual__2025-10-10T21:20:20.026271+00:00 [running]> on host ebots-macbook-pro.local
[2025-10-11T05:23:14.105+0200] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='predict_batch_dag' AIRFLOW_CTX_TASK_ID='send_batch_predictions' AIRFLOW_CTX_EXECUTION_DATE='2025-10-10T21:20:20.026271+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-10T21:20:20.026271+00:00'
[2025-10-11T05:23:14.110+0200] {logging_mixin.py:188} INFO - ðŸ“„ Found CSV file: /Users/ebotfabien/Desktop/school/air_new/dags/destination/data_part_1.csv
[2025-10-11T05:23:14.121+0200] {logging_mixin.py:188} INFO - ðŸ“¦ Sending 10 batch(es)...
[2025-10-11T05:23:43.638+0200] {local_task_job_runner.py:121} ERROR - Received SIGTERM. Terminating subprocesses
[2025-10-11T05:23:43.644+0200] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 57831. PIDs of all processes in the group: [57831]
[2025-10-11T05:23:43.645+0200] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 57831
