[2025-10-10T23:36:23.720+0200] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: predict_batch_dag.send_batch_predictions manual__2025-10-10T21:20:20.026271+00:00 [queued]>
[2025-10-10T23:36:23.722+0200] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: predict_batch_dag.send_batch_predictions manual__2025-10-10T21:20:20.026271+00:00 [queued]>
[2025-10-10T23:36:23.723+0200] {taskinstance.py:2193} INFO - Starting attempt 2 of 1
[2025-10-10T23:36:23.727+0200] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): send_batch_predictions> on 2025-10-10 21:20:20.026271+00:00
[2025-10-10T23:36:23.732+0200] {standard_task_runner.py:60} INFO - Started process 47243 to run task
[2025-10-10T23:36:23.737+0200] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'predict_batch_dag', 'send_batch_predictions', 'manual__2025-10-10T21:20:20.026271+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/prediction_dag.py', '--cfg-path', '/var/folders/rp/syznybx160jd0kg9k7r_sj8w0000gn/T/tmpaubegaly']
[2025-10-10T23:36:23.742+0200] {standard_task_runner.py:88} INFO - Job 107: Subtask send_batch_predictions
[2025-10-10T23:36:23.763+0200] {task_command.py:423} INFO - Running <TaskInstance: predict_batch_dag.send_batch_predictions manual__2025-10-10T21:20:20.026271+00:00 [running]> on host ebots-macbook-pro.local
[2025-10-10T23:36:23.793+0200] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='predict_batch_dag' AIRFLOW_CTX_TASK_ID='send_batch_predictions' AIRFLOW_CTX_EXECUTION_DATE='2025-10-10T21:20:20.026271+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-10T21:20:20.026271+00:00'
[2025-10-10T23:36:23.794+0200] {logging_mixin.py:188} INFO - ðŸ“„ Found CSV file: /Users/ebotfabien/Desktop/school/air_new/dags/destination/data_part_1.csv
[2025-10-10T23:36:23.799+0200] {logging_mixin.py:188} INFO - ðŸ“¦ Sending 10 batch(es)...
[2025-10-10T23:36:37.925+0200] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 47243. PIDs of all processes in the group: [47243]
[2025-10-10T23:36:37.927+0200] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 47243
[2025-10-10T23:37:06.756+0200] {taskinstance.py:1969} INFO - Dependencies not met for <TaskInstance: predict_batch_dag.send_batch_predictions manual__2025-10-10T21:20:20.026271+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2025-10-10T23:37:06.760+0200] {taskinstance.py:1969} INFO - Dependencies not met for <TaskInstance: predict_batch_dag.send_batch_predictions manual__2025-10-10T21:20:20.026271+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2025-10-10T23:37:06.761+0200] {local_task_job_runner.py:160} INFO - Task is not able to be run
[2025-10-10T23:37:22.617+0200] {taskinstance.py:1969} INFO - Dependencies not met for <TaskInstance: predict_batch_dag.send_batch_predictions manual__2025-10-10T21:20:20.026271+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2025-10-10T23:37:22.618+0200] {taskinstance.py:1969} INFO - Dependencies not met for <TaskInstance: predict_batch_dag.send_batch_predictions manual__2025-10-10T21:20:20.026271+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2025-10-10T23:37:22.618+0200] {local_task_job_runner.py:160} INFO - Task is not able to be run
[2025-10-10T23:37:22.900+0200] {taskinstance.py:1969} INFO - Dependencies not met for <TaskInstance: predict_batch_dag.send_batch_predictions manual__2025-10-10T21:20:20.026271+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2025-10-10T23:37:22.900+0200] {taskinstance.py:1969} INFO - Dependencies not met for <TaskInstance: predict_batch_dag.send_batch_predictions manual__2025-10-10T21:20:20.026271+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2025-10-10T23:37:22.903+0200] {local_task_job_runner.py:160} INFO - Task is not able to be run
